/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutPublicRouteImport } from './routes/_layout/_public'
import { Route as LayoutAuthenticatedRouteImport } from './routes/_layout/_authenticated'
import { Route as LayoutPublicIndexRouteImport } from './routes/_layout/_public/index'
import { Route as LayoutPublicSkillRouteImport } from './routes/_layout/_public/skill'
import { Route as LayoutPublicLoginRouteImport } from './routes/_layout/_public/login'
import { Route as LayoutPublicAboutRouteImport } from './routes/_layout/_public/about'
import { Route as LayoutAuthenticatedSettingsRouteImport } from './routes/_layout/_authenticated/settings'
import { Route as LayoutAuthenticatedNostrRouteImport } from './routes/_layout/_authenticated/nostr'
import { Route as LayoutAuthenticatedHomeRouteImport } from './routes/_layout/_authenticated/home'
import { Route as LayoutAuthenticatedAdminRouteImport } from './routes/_layout/_authenticated/admin'
import { Route as LayoutAuthenticatedSettingsIndexRouteImport } from './routes/_layout/_authenticated/settings/index'
import { Route as LayoutAuthenticatedOrganizationsIndexRouteImport } from './routes/_layout/_authenticated/organizations/index'
import { Route as LayoutAuthenticatedAdminIndexRouteImport } from './routes/_layout/_authenticated/admin/index'
import { Route as LayoutAuthenticatedSettingsSecurityRouteImport } from './routes/_layout/_authenticated/settings/security'
import { Route as LayoutAuthenticatedSettingsProfileRouteImport } from './routes/_layout/_authenticated/settings/profile'
import { Route as LayoutAuthenticatedSettingsAuthMethodsRouteImport } from './routes/_layout/_authenticated/settings/auth-methods'
import { Route as LayoutAuthenticatedOrganizationsNewRouteImport } from './routes/_layout/_authenticated/organizations/new'
import { Route as LayoutAuthenticatedOrganizationsSlugRouteImport } from './routes/_layout/_authenticated/organizations/$slug'
import { Route as LayoutAuthenticatedAdminSystemRouteImport } from './routes/_layout/_authenticated/admin/system'
import { Route as LayoutAuthenticatedAcceptInvitationIdRouteImport } from './routes/_layout/_authenticated/accept-invitation.$id'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutPublicRoute = LayoutPublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthenticatedRoute = LayoutAuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutPublicIndexRoute = LayoutPublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicSkillRoute = LayoutPublicSkillRouteImport.update({
  id: '/skill',
  path: '/skill',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicLoginRoute = LayoutPublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutPublicAboutRoute = LayoutPublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LayoutPublicRoute,
} as any)
const LayoutAuthenticatedSettingsRoute =
  LayoutAuthenticatedSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedNostrRoute =
  LayoutAuthenticatedNostrRouteImport.update({
    id: '/nostr',
    path: '/nostr',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedHomeRoute = LayoutAuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => LayoutAuthenticatedRoute,
} as any)
const LayoutAuthenticatedAdminRoute =
  LayoutAuthenticatedAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedSettingsIndexRoute =
  LayoutAuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedOrganizationsIndexRoute =
  LayoutAuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminIndexRoute =
  LayoutAuthenticatedAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => LayoutAuthenticatedAdminRoute,
  } as any)
const LayoutAuthenticatedSettingsSecurityRoute =
  LayoutAuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsProfileRoute =
  LayoutAuthenticatedSettingsProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedSettingsAuthMethodsRoute =
  LayoutAuthenticatedSettingsAuthMethodsRouteImport.update({
    id: '/auth-methods',
    path: '/auth-methods',
    getParentRoute: () => LayoutAuthenticatedSettingsRoute,
  } as any)
const LayoutAuthenticatedOrganizationsNewRoute =
  LayoutAuthenticatedOrganizationsNewRouteImport.update({
    id: '/organizations/new',
    path: '/organizations/new',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedOrganizationsSlugRoute =
  LayoutAuthenticatedOrganizationsSlugRouteImport.update({
    id: '/organizations/$slug',
    path: '/organizations/$slug',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)
const LayoutAuthenticatedAdminSystemRoute =
  LayoutAuthenticatedAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => LayoutAuthenticatedAdminRoute,
  } as any)
const LayoutAuthenticatedAcceptInvitationIdRoute =
  LayoutAuthenticatedAcceptInvitationIdRouteImport.update({
    id: '/accept-invitation/$id',
    path: '/accept-invitation/$id',
    getParentRoute: () => LayoutAuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutPublicIndexRoute
  '/admin': typeof LayoutAuthenticatedAdminRouteWithChildren
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/nostr': typeof LayoutAuthenticatedNostrRoute
  '/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/about': typeof LayoutPublicAboutRoute
  '/login': typeof LayoutPublicLoginRoute
  '/skill': typeof LayoutPublicSkillRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/admin/system': typeof LayoutAuthenticatedAdminSystemRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/admin/': typeof LayoutAuthenticatedAdminIndexRoute
  '/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutPublicIndexRoute
  '/home': typeof LayoutAuthenticatedHomeRoute
  '/nostr': typeof LayoutAuthenticatedNostrRoute
  '/about': typeof LayoutPublicAboutRoute
  '/login': typeof LayoutPublicLoginRoute
  '/skill': typeof LayoutPublicSkillRoute
  '/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/admin/system': typeof LayoutAuthenticatedAdminSystemRoute
  '/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/admin': typeof LayoutAuthenticatedAdminIndexRoute
  '/organizations': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/settings': typeof LayoutAuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/_authenticated': typeof LayoutAuthenticatedRouteWithChildren
  '/_layout/_public': typeof LayoutPublicRouteWithChildren
  '/_layout/_authenticated/admin': typeof LayoutAuthenticatedAdminRouteWithChildren
  '/_layout/_authenticated/home': typeof LayoutAuthenticatedHomeRoute
  '/_layout/_authenticated/nostr': typeof LayoutAuthenticatedNostrRoute
  '/_layout/_authenticated/settings': typeof LayoutAuthenticatedSettingsRouteWithChildren
  '/_layout/_public/about': typeof LayoutPublicAboutRoute
  '/_layout/_public/login': typeof LayoutPublicLoginRoute
  '/_layout/_public/skill': typeof LayoutPublicSkillRoute
  '/_layout/_public/': typeof LayoutPublicIndexRoute
  '/_layout/_authenticated/accept-invitation/$id': typeof LayoutAuthenticatedAcceptInvitationIdRoute
  '/_layout/_authenticated/admin/system': typeof LayoutAuthenticatedAdminSystemRoute
  '/_layout/_authenticated/organizations/$slug': typeof LayoutAuthenticatedOrganizationsSlugRoute
  '/_layout/_authenticated/organizations/new': typeof LayoutAuthenticatedOrganizationsNewRoute
  '/_layout/_authenticated/settings/auth-methods': typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  '/_layout/_authenticated/settings/profile': typeof LayoutAuthenticatedSettingsProfileRoute
  '/_layout/_authenticated/settings/security': typeof LayoutAuthenticatedSettingsSecurityRoute
  '/_layout/_authenticated/admin/': typeof LayoutAuthenticatedAdminIndexRoute
  '/_layout/_authenticated/organizations/': typeof LayoutAuthenticatedOrganizationsIndexRoute
  '/_layout/_authenticated/settings/': typeof LayoutAuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/home'
    | '/nostr'
    | '/settings'
    | '/about'
    | '/login'
    | '/skill'
    | '/accept-invitation/$id'
    | '/admin/system'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/admin/'
    | '/organizations/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/nostr'
    | '/about'
    | '/login'
    | '/skill'
    | '/accept-invitation/$id'
    | '/admin/system'
    | '/organizations/$slug'
    | '/organizations/new'
    | '/settings/auth-methods'
    | '/settings/profile'
    | '/settings/security'
    | '/admin'
    | '/organizations'
    | '/settings'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/_authenticated'
    | '/_layout/_public'
    | '/_layout/_authenticated/admin'
    | '/_layout/_authenticated/home'
    | '/_layout/_authenticated/nostr'
    | '/_layout/_authenticated/settings'
    | '/_layout/_public/about'
    | '/_layout/_public/login'
    | '/_layout/_public/skill'
    | '/_layout/_public/'
    | '/_layout/_authenticated/accept-invitation/$id'
    | '/_layout/_authenticated/admin/system'
    | '/_layout/_authenticated/organizations/$slug'
    | '/_layout/_authenticated/organizations/new'
    | '/_layout/_authenticated/settings/auth-methods'
    | '/_layout/_authenticated/settings/profile'
    | '/_layout/_authenticated/settings/security'
    | '/_layout/_authenticated/admin/'
    | '/_layout/_authenticated/organizations/'
    | '/_layout/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/_public': {
      id: '/_layout/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_authenticated': {
      id: '/_layout/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutAuthenticatedRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_public/': {
      id: '/_layout/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutPublicIndexRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/skill': {
      id: '/_layout/_public/skill'
      path: '/skill'
      fullPath: '/skill'
      preLoaderRoute: typeof LayoutPublicSkillRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/login': {
      id: '/_layout/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LayoutPublicLoginRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_public/about': {
      id: '/_layout/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LayoutPublicAboutRouteImport
      parentRoute: typeof LayoutPublicRoute
    }
    '/_layout/_authenticated/settings': {
      id: '/_layout/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/nostr': {
      id: '/_layout/_authenticated/nostr'
      path: '/nostr'
      fullPath: '/nostr'
      preLoaderRoute: typeof LayoutAuthenticatedNostrRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/home': {
      id: '/_layout/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof LayoutAuthenticatedHomeRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/admin': {
      id: '/_layout/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAuthenticatedAdminRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/settings/': {
      id: '/_layout/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/organizations/': {
      id: '/_layout/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/admin/': {
      id: '/_layout/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof LayoutAuthenticatedAdminIndexRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRoute
    }
    '/_layout/_authenticated/settings/security': {
      id: '/_layout/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/profile': {
      id: '/_layout/_authenticated/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsProfileRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/settings/auth-methods': {
      id: '/_layout/_authenticated/settings/auth-methods'
      path: '/auth-methods'
      fullPath: '/settings/auth-methods'
      preLoaderRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRouteImport
      parentRoute: typeof LayoutAuthenticatedSettingsRoute
    }
    '/_layout/_authenticated/organizations/new': {
      id: '/_layout/_authenticated/organizations/new'
      path: '/organizations/new'
      fullPath: '/organizations/new'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsNewRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/organizations/$slug': {
      id: '/_layout/_authenticated/organizations/$slug'
      path: '/organizations/$slug'
      fullPath: '/organizations/$slug'
      preLoaderRoute: typeof LayoutAuthenticatedOrganizationsSlugRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
    '/_layout/_authenticated/admin/system': {
      id: '/_layout/_authenticated/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof LayoutAuthenticatedAdminSystemRouteImport
      parentRoute: typeof LayoutAuthenticatedAdminRoute
    }
    '/_layout/_authenticated/accept-invitation/$id': {
      id: '/_layout/_authenticated/accept-invitation/$id'
      path: '/accept-invitation/$id'
      fullPath: '/accept-invitation/$id'
      preLoaderRoute: typeof LayoutAuthenticatedAcceptInvitationIdRouteImport
      parentRoute: typeof LayoutAuthenticatedRoute
    }
  }
}

interface LayoutAuthenticatedAdminRouteChildren {
  LayoutAuthenticatedAdminSystemRoute: typeof LayoutAuthenticatedAdminSystemRoute
  LayoutAuthenticatedAdminIndexRoute: typeof LayoutAuthenticatedAdminIndexRoute
}

const LayoutAuthenticatedAdminRouteChildren: LayoutAuthenticatedAdminRouteChildren =
  {
    LayoutAuthenticatedAdminSystemRoute: LayoutAuthenticatedAdminSystemRoute,
    LayoutAuthenticatedAdminIndexRoute: LayoutAuthenticatedAdminIndexRoute,
  }

const LayoutAuthenticatedAdminRouteWithChildren =
  LayoutAuthenticatedAdminRoute._addFileChildren(
    LayoutAuthenticatedAdminRouteChildren,
  )

interface LayoutAuthenticatedSettingsRouteChildren {
  LayoutAuthenticatedSettingsAuthMethodsRoute: typeof LayoutAuthenticatedSettingsAuthMethodsRoute
  LayoutAuthenticatedSettingsProfileRoute: typeof LayoutAuthenticatedSettingsProfileRoute
  LayoutAuthenticatedSettingsSecurityRoute: typeof LayoutAuthenticatedSettingsSecurityRoute
  LayoutAuthenticatedSettingsIndexRoute: typeof LayoutAuthenticatedSettingsIndexRoute
}

const LayoutAuthenticatedSettingsRouteChildren: LayoutAuthenticatedSettingsRouteChildren =
  {
    LayoutAuthenticatedSettingsAuthMethodsRoute:
      LayoutAuthenticatedSettingsAuthMethodsRoute,
    LayoutAuthenticatedSettingsProfileRoute:
      LayoutAuthenticatedSettingsProfileRoute,
    LayoutAuthenticatedSettingsSecurityRoute:
      LayoutAuthenticatedSettingsSecurityRoute,
    LayoutAuthenticatedSettingsIndexRoute:
      LayoutAuthenticatedSettingsIndexRoute,
  }

const LayoutAuthenticatedSettingsRouteWithChildren =
  LayoutAuthenticatedSettingsRoute._addFileChildren(
    LayoutAuthenticatedSettingsRouteChildren,
  )

interface LayoutAuthenticatedRouteChildren {
  LayoutAuthenticatedAdminRoute: typeof LayoutAuthenticatedAdminRouteWithChildren
  LayoutAuthenticatedHomeRoute: typeof LayoutAuthenticatedHomeRoute
  LayoutAuthenticatedNostrRoute: typeof LayoutAuthenticatedNostrRoute
  LayoutAuthenticatedSettingsRoute: typeof LayoutAuthenticatedSettingsRouteWithChildren
  LayoutAuthenticatedAcceptInvitationIdRoute: typeof LayoutAuthenticatedAcceptInvitationIdRoute
  LayoutAuthenticatedOrganizationsSlugRoute: typeof LayoutAuthenticatedOrganizationsSlugRoute
  LayoutAuthenticatedOrganizationsNewRoute: typeof LayoutAuthenticatedOrganizationsNewRoute
  LayoutAuthenticatedOrganizationsIndexRoute: typeof LayoutAuthenticatedOrganizationsIndexRoute
}

const LayoutAuthenticatedRouteChildren: LayoutAuthenticatedRouteChildren = {
  LayoutAuthenticatedAdminRoute: LayoutAuthenticatedAdminRouteWithChildren,
  LayoutAuthenticatedHomeRoute: LayoutAuthenticatedHomeRoute,
  LayoutAuthenticatedNostrRoute: LayoutAuthenticatedNostrRoute,
  LayoutAuthenticatedSettingsRoute:
    LayoutAuthenticatedSettingsRouteWithChildren,
  LayoutAuthenticatedAcceptInvitationIdRoute:
    LayoutAuthenticatedAcceptInvitationIdRoute,
  LayoutAuthenticatedOrganizationsSlugRoute:
    LayoutAuthenticatedOrganizationsSlugRoute,
  LayoutAuthenticatedOrganizationsNewRoute:
    LayoutAuthenticatedOrganizationsNewRoute,
  LayoutAuthenticatedOrganizationsIndexRoute:
    LayoutAuthenticatedOrganizationsIndexRoute,
}

const LayoutAuthenticatedRouteWithChildren =
  LayoutAuthenticatedRoute._addFileChildren(LayoutAuthenticatedRouteChildren)

interface LayoutPublicRouteChildren {
  LayoutPublicAboutRoute: typeof LayoutPublicAboutRoute
  LayoutPublicLoginRoute: typeof LayoutPublicLoginRoute
  LayoutPublicSkillRoute: typeof LayoutPublicSkillRoute
  LayoutPublicIndexRoute: typeof LayoutPublicIndexRoute
}

const LayoutPublicRouteChildren: LayoutPublicRouteChildren = {
  LayoutPublicAboutRoute: LayoutPublicAboutRoute,
  LayoutPublicLoginRoute: LayoutPublicLoginRoute,
  LayoutPublicSkillRoute: LayoutPublicSkillRoute,
  LayoutPublicIndexRoute: LayoutPublicIndexRoute,
}

const LayoutPublicRouteWithChildren = LayoutPublicRoute._addFileChildren(
  LayoutPublicRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthenticatedRoute: typeof LayoutAuthenticatedRouteWithChildren
  LayoutPublicRoute: typeof LayoutPublicRouteWithChildren
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthenticatedRoute: LayoutAuthenticatedRouteWithChildren,
  LayoutPublicRoute: LayoutPublicRouteWithChildren,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
