import { eventIterator, oc } from "every-plugin/orpc";
import { z } from "every-plugin/zod";

// Define specific errors thrown by this plugin
const Errors = {
  UNAUTHORIZED: {
    status: 401,
    message: "User ID required",
  },
  FORBIDDEN: {
    status: 403,
    message: "Operation not permitted",
  },
  NOT_FOUND: {
    status: 404,
    message: "Failed to fetch item: Item not found",
  },
  CONFLICT: {
    status: 409,
    message: "A thing with this ID already exists",
  },
  BAD_REQUEST: {
    status: 400,
    message: "Bad request",
  },
};

const ErrorTestKindSchema = z.enum([
  "unauthorized",
  "forbidden",
  "not_found",
  "conflict",
  "bad_request",
  "internal",
]);

// Schema for the data items this plugin provides
export const ItemSchema = z.object({
  id: z.string().describe("Unique identifier for the item"),
  title: z.string().describe("Title or name of the item"),
  createdAt: z.string().datetime().describe("ISO 8601 timestamp when the item was created"),
});

// Schema for search results
export const SearchResultSchema = z.object({
  item: ItemSchema,
  score: z.number().min(0).max(1).describe("Relevance score between 0 and 1"),
});

// Schema for background broadcast events (MemoryPublisher)
export const BackgroundEventSchema = z.object({
  id: z.string().describe("Unique identifier for the background event"),
  index: z.number().describe("Sequential index of the event"),
  timestamp: z.number().describe("Unix timestamp in milliseconds when the event was created"),
});

export const ThingSchema = z.object({
  thingId: z.string().describe("Unique identifier for the thing"),
  type: z.string().describe("Plugin-derived thing type"),
  payload: z.unknown().describe("Plugin-owned thing payload"),
  createdAt: z.string().datetime().describe("ISO 8601 timestamp when the thing was created"),
  updatedAt: z.string().datetime().describe("ISO 8601 timestamp when the thing was last updated"),
});

export const CreatedThingSchema = ThingSchema.extend({
  action: z.string().describe("Action emitted for the creation, e.g. template.note.created"),
});

export const ListThingsSchema = z.object({
  data: z.array(ThingSchema).describe("List of things matching the query"),
  meta: z.object({
    total: z.number().describe("Total number of matching things"),
    hasMore: z.boolean().describe("Whether another page of results exists"),
    nextCursor: z.string().nullable().describe("Opaque cursor for the next page, or null if done"),
  }),
});

// oRPC Contract definition
export const contract = oc.router({
  // Single item lookup by ID
  getById: oc
    .route({
      method: "GET",
      path: "/items/{id}",
      summary: "Get item by ID",
      description:
        "Fetches a single item by its unique identifier. This is the primary method for retrieving individual items. Requires authentication.",
      tags: ["Items"],
    })
    .input(
      z.object({
        id: z.string().min(1, "ID is required").describe("Unique item identifier"),
      }),
    )
    .output(
      z.object({
        item: ItemSchema,
        userId: z.string().describe("ID of the authenticated user who made the request"),
      }),
    )
    .errors(Errors),

  // Search with server-side streaming
  search: oc
    .route({
      method: "GET",
      path: "/search",
      summary: "Search items",
      description:
        "Performs a search across items with server-side streaming. Returns results as they become available for better performance.",
      tags: ["Items", "Search"],
    })
    .input(
      z.object({
        query: z.string().min(1, "Query is required").describe("Search query string"),
        limit: z
          .number()
          .min(1)
          .max(100)
          .default(10)
          .describe("Maximum number of results to return"),
      }),
    )
    .output(eventIterator(SearchResultSchema)), // Notice "eventIterator", this enables streaming

  // Health check procedure
  ping: oc
    .route({
      method: "GET",
      path: "/ping",
      summary: "Health check",
      description: "Simple ping endpoint to verify the plugin is responding correctly.",
      tags: ["Health"],
    })
    .output(
      z.object({
        status: z.literal("ok").describe('Always returns "ok" if the service is healthy'),
        timestamp: z
          .string()
          .datetime()
          .describe("ISO 8601 timestamp of when the ping was processed"),
      }),
    ),

  // Background streaming with resume support (MemoryPublisher)
  listenBackground: oc
    .route({
      method: "GET",
      path: "/background/events",
      summary: "Listen to background events",
      description:
        "Streams background events generated by the plugin. Supports resume from last event ID for serverless environments.",
      tags: ["Streaming", "Background"],
    })
    .input(
      z.object({
        maxResults: z
          .number()
          .min(1)
          .max(100)
          .optional()
          .describe("Maximum number of events to return"),
        lastEventId: z
          .string()
          .optional()
          .describe("Resume from this event ID (for serverless resume)"),
      }),
    )
    .output(eventIterator(BackgroundEventSchema)),

  // Manual background event publishing
  enqueueBackground: oc
    .route({
      method: "POST",
      path: "/background/events",
      summary: "Enqueue background event",
      description:
        "Manually adds an event to the background stream. Useful for testing event broadcasting.",
      tags: ["Background", "Testing"],
    })
    .input(
      z.object({
        id: z.string().optional().describe("Optional custom event ID"),
      }),
    )
    .output(
      z.object({
        ok: z.boolean().describe("True if the event was successfully enqueued"),
      }),
    ),

  createThing: oc
    .route({
      method: "POST",
      path: "/things",
      summary: "Create a thing",
      description: "Creates a DB-backed thing and returns it",
      tags: ["Things"],
    })
    .input(
      z.object({
        thingId: z.string().min(1, "Thing ID is required"),
        payload: z.unknown(),
      }),
    )
    .output(CreatedThingSchema)
    .errors({ CONFLICT: Errors.CONFLICT }),

  getThing: oc
    .route({
      method: "GET",
      path: "/things/{thingId}",
      summary: "Get a thing",
      description: "Returns the DB-backed thing by ID",
      tags: ["Things"],
    })
    .input(
      z.object({
        thingId: z.string().min(1, "Thing ID is required"),
      }),
    )
    .output(ThingSchema)
    .errors({ NOT_FOUND: { status: 404, message: "Thing not found" } }),

  listThings: oc
    .route({
      method: "GET",
      path: "/things",
      summary: "List things",
      description:
        "Lists things with optional type filtering and offset-based cursor pagination, ordered by newest first.",
      tags: ["Things"],
    })
    .input(
      z.object({
        type: z.string().optional().describe("Filter by thing type"),
        limit: z
          .number()
          .min(1)
          .max(100)
          .default(10)
          .describe("Maximum number of results to return"),
        cursor: z.string().optional().describe("Opaque cursor for the next page"),
      }),
    )
    .output(ListThingsSchema),

  deleteThing: oc
    .route({
      method: "DELETE",
      path: "/things/{thingId}",
      summary: "Delete a thing",
      description: "Removes the DB-backed thing by ID",
      tags: ["Things"],
    })
    .input(
      z.object({
        thingId: z.string().min(1, "Thing ID is required"),
      }),
    )
    .output(z.object({ success: z.literal(true) }))
    .errors({ NOT_FOUND: { status: 404, message: "Thing not found" } }),

  testError: oc
    .route({
      method: "GET",
      path: "/errors",
      summary: "Trigger a specific error kind",
      description:
        "Regression-test helper that throws the requested error kind so the host error surface can be validated.",
      tags: ["Testing"],
    })
    .input(
      z.object({
        kind: ErrorTestKindSchema.describe("Which error kind to trigger"),
      }),
    )
    .output(
      z.object({
        ok: z.literal(true).describe("Always true when no error is thrown"),
      }),
    )
    .errors({
      UNAUTHORIZED: Errors.UNAUTHORIZED,
      FORBIDDEN: Errors.FORBIDDEN,
      NOT_FOUND: Errors.NOT_FOUND,
      CONFLICT: Errors.CONFLICT,
      BAD_REQUEST: Errors.BAD_REQUEST,
    }),
});

export type ContractType = typeof contract;
